version: '3'
services:
    db:
        image: postgres:latest
        restart: always
        expose:
          - "5432"
        environment:
          POSTGRES_USER: test123
          POSTGRES_PASSWORD: pw1234
          POSTGRES_DB: base123
    web:
        build: .
        command: python app/manage.py runserver 0.0.0.0:8000
        restart: always
        volumes:
            - .:/app_docker
        ports:
            - "8000:8000"
        depends_on:
            - db
        links:
            - db:db

